retain_public: true
# The report the cycle-watch workflow reads is written by JSONEncoder and read by jq, so its
# properties have no Swift reader for Periphery to find.
retain_codable_properties: true
